### ISSUE TITLE
Factor out sparse Hessian code

### ISSUE THREAD

**Issue by ElOceanografo** [ElOceanografo/MarginalLogDensities.jl#10]
The sparse Hessian coloring/decompression code in this package has been improved and incorporated into SparseDiffTools.jl (https://github.com/JuliaDiff/SparseDiffTools.jl/pull/190). Should replace it with that implementation.

**Comment by slwu89** [comment]
@ElOceanografo I looked a bit at the SparseDiffTools, when using `ForwardColorHesCache` to set up the stuff needed to more efficiently compute the Hessian I encountered some errors during testing related to array dimensions not matching.

I suspect the problem is that I'm setting up the `ForwardColorHesCache` wrong (https://github.com/slwu89/MarginalLogDensities.jl/blob/SparseHess/src/MarginalLogDensities.jl#L111). Am I right in assuming that when calling it in `HessianConfig` we want the function passed to it (`f` argument) to take as arguments only the parameters to marginalize over, rather than the full vector $\theta$?
