### ISSUE TITLE
Why not in regisry?

### ISSUE THREAD

**Issue by PharmCat** [ElOceanografo/MarginalLogDensities.jl#8]
Hi! Why not in regisry?

**Comment by ElOceanografo** [comment]
Basically because this is an early-stage proof-of-concept that I haven't had enough time to devote to lately. Some parts of the code that I wrote as patches in this repo have since been moved to [base](https://github.com/JuliaLang/julia/pull/40716) and SparseDiffTools (in progress), so there's some refactoring I'd want to do before releasing this package.  That said, I'll definitely consider it if there's interest.

**Comment by PharmCat** [comment]
> Basically because this is an early-stage proof-of-concept that I haven't had enough time to devote to lately. 

Hi! Thank you for reply! I  think about implementation FOCE/FOCE-I approximation and looking for repo with similar  aims. It will be very impressive if it will be possible in this repo.

**Comment by ElOceanografo** [comment]
Registration has just been submitted! https://github.com/ElOceanografo/MarginalLogDensities.jl/commit/e9df0aa3de22712fab7a49bcab77c945d6d93f31#commitcomment-116228989
